version: '3.8'

services:
  app:
    image: sarveshalt/java-app:latest  # Docker image to use (replace with your image)
    build: .
    ports:
      - "8080:8080"  # Expose the app on port 8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod  # Example environment variable (adjust for your app)
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
