name: Java CI with Gradle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-java:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Echo message
      run: echo "Hi, I am from COSC 1209 class"
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8 (Temurin)
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests with Gradle
      run: ./gradlew test

    # Install Docker on macOS
    - name: Install Docker on macOS
      if: runner.os == 'macOS'
      run: |
        brew install --cask docker
        open /Applications/Docker.app
        # Give Docker a few seconds to start
        sleep 30
        # Wait for Docker to be ready
        docker --version

    # Set up Docker Buildx (Platform-Specific)
    - name: Set up Docker Buildx (macOS/Ubuntu only)
      if: runner.os == 'macOS' || runner.os == 'ubuntu-latest'
      uses: docker/setup-buildx-action@v2
      with:
        version: latest
        driver: docker-container
        buildkitd-flags: "--allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host"
        install: false
        use: true

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build Docker image
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: docker.io/sarveshalt/java-app:latest
        platform: linux/amd64  # Specify the platform to ensure cross-OS compatibility
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
