name: Java CI with Gradle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-java:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Echo message
        run: echo "Hi, I am from COSC 1209 class"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
          java-package: 'jdk'
          check-latest: false
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true

      # Handle Windows-specific Gradle wrapper
      - name: Set Gradle wrapper permissions (Unix)
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      # Build and test with Gradle (Windows)
      - name: Build and test with Gradle (Windows)
        if: runner.os == 'Windows'
        run: |
          ./gradlew.bat build
          ./gradlew.bat test
        shell: cmd

      # Build and test with Gradle (Unix)
      - name: Build and test with Gradle (Unix)
        if: runner.os != 'Windows'
        run: |
          ./gradlew build
          ./gradlew test
        shell: bash

      # - name: Setup Docker for macOS
      #   if: runner.os == 'macOS'
      #   run: |
      #     brew install --cask docker
      #     which docker
      #     open -a docker
      #     while ! docker system info > /dev/null 2>&1; do
      #       echo "Waiting for Docker to start..."
      #       sleep 2
      #     done
      #     docker --version 

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if Docker is installed
        run: which docker || echo "Docker not found"

      - name: Install Docker if not found
        run: |
          brew install --cask docker
          open /Applications/Docker.app
          sleep 30

      - name: Check Docker info
        run: docker info || echo "Docker daemon is not running"

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          driver: docker-container
          buildkitd-flags: --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
          use: true
          cleanup: true

      - name: Build Docker image using Buildx
        run: docker buildx build --tag my-image .

                    
      # Docker is pre-installed on Ubuntu runners
      - name: Verify Docker (Ubuntu)
        if: runner.os == 'Linux'
        run: docker --version

      # Docker Desktop for Windows
      - name: Verify Docker (Windows)
        if: runner.os == 'Windows'
        run: |
          docker --version
        shell: pwsh

      # Set up Docker Buildx (Skip for Windows)
      - name: Set up Docker Buildx
        if: runner.os != 'Windows'
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

     # Build and push Docker image (Windows)
      - name: Build and push Docker image (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          Write-Host "Starting Windows Docker build..."
          
          # Create Windows-specific Dockerfile
          @"
          FROM mcr.microsoft.com/windows/nanoserver:1809
          
          WORKDIR C:/app
          COPY ./build/libs/java-app-1.0-SNAPSHOT.jar .
          
          EXPOSE 8080
          
          ENTRYPOINT ["java", "-jar", "java-app-1.0-SNAPSHOT.jar"]
          "@ | Out-File -Encoding ASCII Dockerfile.windows
          
          docker build -f Dockerfile.windows -t ${{ secrets.DOCKER_USERNAME }}/java-app:windows-latest .
          if ($LASTEXITCODE -ne 0) {
              Write-Host "Docker build failed"
              exit 1
          }
          
          docker push ${{ secrets.DOCKER_USERNAME }}/java-app:windows-latest
          if ($LASTEXITCODE -ne 0) {
              Write-Host "Docker push failed"
              exit 1
          }
      # Build and Push Docker image for Unix systems
      - name: Build and Push Docker image (Unix)
        if: runner.os != 'Windows'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: docker.io/sarveshalt/java-app:latest
          platforms: linux/amd64
          cache-from: type=registry,ref=docker.io/sarveshalt/java-app:buildcache
          cache-to: type=registry,ref=docker.io/sarveshalt/java-app:buildcache,mode=max