name: Java CI with Gradle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-java:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Echo message
        run: echo "Hi, I am from COSC 1209 class"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
          java-package: 'jdk'
          check-latest: false
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true

      # Handle Gradle wrapper permissions on Unix systems (Linux/macOS)
      - name: Set Gradle wrapper permissions (Unix)
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      # Build and test with Gradle (Windows)
      - name: Build and test with Gradle (Windows)
        if: runner.os == 'Windows'
        run: |
          .\gradlew.bat build
          .\gradlew.bat test
        shell: cmd

      # Build and test with Gradle (Linux/macOS)
      - name: Build and test with Gradle (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          ./gradlew build
          ./gradlew test
        shell: bash

      # Docker setup and installation for macOS
      - name: Install Docker on macOS
        if: runner.os == 'macos-latest'
        run
