name: Java CI with Gradle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-java:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Echo message
        run: echo "Hi, I am from COSC 1209 class"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
          java-package: 'jdk'
          check-latest: false
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true

      # Handle Windows-specific Gradle wrapper
      - name: Set Gradle wrapper permissions (Unix)
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      # Build and test with Gradle (Windows)
      - name: Build and test with Gradle (Windows)
        if: runner.os == 'Windows'
        run: |
          ./gradlew.bat build
          ./gradlew.bat test
        shell: cmd

      # Build and test with Gradle (Unix)
      - name: Build and test with Gradle (Unix)
        if: runner.os != 'Windows'
        run: |
          ./gradlew build
          ./gradlew test
        shell: bash

      # - name: Setup Docker for macOS
      #   if: runner.os == 'macOS'
      #   run: |
      #     brew install --cask docker
      #     which docker
      #     open -a docker
      #     while ! docker system info > /dev/null 2>&1; do
      #       echo "Waiting for Docker to start..."
      #       sleep 2
      #     done
      #     docker --version 
      
      - name: Setup Docker for macOS
        if: runner.os == 'macOS'
        run: |
          # Install Docker using Homebrew
          echo "Installing Docker..."
          brew install --cask docker
          
          # Add Docker to PATH explicitly (for CI/CD environment)
          export PATH="/Applications/Docker.app/Contents/Resources/bin:$PATH"
          
          # Verify if docker command is in the PATH
          echo "Checking Docker binary location..."
          which docker
          echo "Docker location: $(which docker)"
          
          # Ensure Docker is accessible
          if ! command -v docker &> /dev/null
          then
              echo "Docker could not be found. Exiting setup."
              exit 1
          fi
          
          # Run Docker from its location with sudo
          echo "Running Docker from its location with sudo..."
          sudo /Applications/Docker.app/Contents/Resources/bin/docker --version
          
          # Open Docker Desktop application using full path (with sudo if needed)
          echo "Attempting to open Docker Desktop with full path..."
          sudo open -a /Applications/Docker.app
          
          # Wait for Docker daemon to be ready (increased wait time)
          echo "Waiting for Docker to start..."
          MAX_WAIT=600  # Increased max wait time (10 minutes)
          WAIT_TIME=0
          while ! sudo /Applications/Docker.app/Contents/Resources/bin/docker system info > /dev/null 2>&1; do
            if [ $WAIT_TIME -ge $MAX_WAIT ]; then
              echo "Timeout reached. Docker didn't start in time."
              exit 1
            fi
            echo "Waiting for Docker to start... ($WAIT_TIME seconds)"
            sleep 10  # Wait 10 seconds before checking again
            WAIT_TIME=$((WAIT_TIME + 10))
          done
          
          # Once Docker is ready, check the Docker version again
          echo "Docker is running!"
          sudo /Applications/Docker.app/Contents/Resources/bin/docker --version
      
    

      
                    
      # Docker is pre-installed on Ubuntu runners
      - name: Verify Docker (Ubuntu)
        if: runner.os == 'Linux'
        run: docker --version

      # Docker Desktop for Windows
      - name: Verify Docker (Windows)
        if: runner.os == 'Windows'
        run: |
          docker --version
        shell: pwsh

      # Set up Docker Buildx (Skip for Windows)
      - name: Set up Docker Buildx
        if: runner.os != 'Windows'
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

     # Build and push Docker image (Windows)
      - name: Build and push Docker image (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          Write-Host "Starting Windows Docker build..."
          
          # Create Windows-specific Dockerfile
          @"
          FROM mcr.microsoft.com/windows/nanoserver:1809
          
          WORKDIR C:/app
          COPY ./build/libs/java-app-1.0-SNAPSHOT.jar .
          
          EXPOSE 8080
          
          ENTRYPOINT ["java", "-jar", "java-app-1.0-SNAPSHOT.jar"]
          "@ | Out-File -Encoding ASCII Dockerfile.windows
          
          docker build -f Dockerfile.windows -t ${{ secrets.DOCKER_USERNAME }}/java-app:windows-latest .
          if ($LASTEXITCODE -ne 0) {
              Write-Host "Docker build failed"
              exit 1
          }
          
          docker push ${{ secrets.DOCKER_USERNAME }}/java-app:windows-latest
          if ($LASTEXITCODE -ne 0) {
              Write-Host "Docker push failed"
              exit 1
          }
      # Build and Push Docker image for Unix systems
      - name: Build and Push Docker image (Unix)
        if: runner.os != 'Windows'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: docker.io/sarveshalt/java-app:latest
          platforms: linux/amd64
          cache-from: type=registry,ref=docker.io/sarveshalt/java-app:buildcache
          cache-to: type=registry,ref=docker.io/sarveshalt/java-app:buildcache,mode=max